--SKRIPT KOJI SE KORISTI ZA INICIJALIZACIJU TABELA BAZE PODATAKA.

--BICE POTREBAN JEDAN SELECT UPIT KOJI IZDVAJA PODATKE O PROIZVODIMA KOJI CIJI NAZIV UNOSI KORISNIK, NJEGA TREBA
--DEFINISATI U OKVIRU C++ PROGRAMA.
-----------------------------------------------------------------------------------------------------------------

--INSERT INTO KORISNIK VALUES

--INSERT INTO ADMINISTRATOR VALUES
--INSERT INTO UPRAVNIK VALUES
--INSERT INTO APOTEKAR VALUES

--INSERT INTO PROIZVOD VALUES
--INSERT INTO PREPARAT VALUES
--INSERT INTO GOTOV VALUES

--INSERT INTO RACUN VALUES
--INSERT INTO KUPOVINA VALUES
--INSERT INTO MAGACIN VALUES
--INSERT INTO DOBAVLJAC VALUES 
----------------------------------------------------------------------------------------------------------------------
